### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jpsheehan** [ipfs-inactive/reading-list#7]
Within the README.md, the following link is broken and returns a 404 error: Baumgart, Ingmar and Mies, Sebastian (2007) S/Kademlia: A Practicable Approach Towards Secure Key-Based Routing.

**Comment by dinfer** [comment]
S/Kademlia: A Practicable Approach Towards Secure Key-Based Routing

I cannot this link too.

**Comment by geofarmbuilder** [comment]
Link is broken again. Thanks

**Comment by gwenf** [comment]
It seems like this repo isn't maintained anymore. I am making a fork in my own account with current updates.
~https://github.com/gwenf/reading-list~

EDIT: this is fixed now. Thanks.

**Comment by Stebalien** [comment]
Ideally, we'd just put all of these papers into IPFS. However, as a US-based company, there are unfortunate legal problems with that solution.

**Comment by daviddias** [comment]
Seems that the link is now fixed. Thanks for reporting and fixing. Closing this one now :)
